<a href="https://colab.research.google.com/github/bragonzu/CursoPython/blob/main/T2_1_DATA_WRANGLING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#DATA WRANGLING - CIRUGIA DE DATOS

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv("datasets/customer-churn-model/Customer Churn Model.txt")

In [ ]:
data

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,414-4276,no,yes,36,156.2,77,26.55,...,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False.
3329,WV,68,415,370-3271,no,no,0,231.1,57,39.29,...,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False.
3330,RI,28,510,328-8230,no,no,0,180.8,109,30.74,...,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False.
3331,CT,184,510,364-6381,yes,no,0,213.8,105,36.35,...,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False.
3332,TN,74,415,400-4344,no,yes,25,234.4,113,39.85,...,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False.

In [ ]:
#CREAR UN SUBCONJUNTO DE DATOS

In [ ]:
account_length=data['Account Length']
account_length

0       128
1       107
2       137
3        84
4        75
       ...
3328    192
3329     68
3330     28
3331    184
3332     74
Name: Account Length, Length: 3333, dtype: int64

In [ ]:
type(account_length)

pandas.core.series.Series

In [ ]:
subset=data[["Account Length","Phone","Eve Charge","Day Calls"]]
subset

      Account Length     Phone  Eve Charge  Day Calls
0                128  382-4657       16.78        110
1                107  371-7191       16.62        123
2                137  358-1921       10.30        114
3                 84  375-9999        5.26         71
4                 75  330-6626       12.61        113
...              ...       ...         ...        ...
3328             192  414-4276       18.32         77
3329              68  370-3271       13.04         57
3330              28  328-8230       24.55        109
3331             184  364-6381       13.57        105
3332              74  400-4344       22.60        113

[3333 rows x 4 columns]

In [ ]:
desired_columns=["Account Length","Phone","Eve Charge","Day Calls"]
desired_columns

['Account Length', 'Phone', 'Eve Charge', 'Day Calls']

In [ ]:

all_columns_list=data.columns.values.tolist()
all_columns_list

['State',
 'Account Length',
 'Area Code',
 'Phone',
 "Int'l Plan",
 'VMail Plan',
 'VMail Message',
 'Day Mins',
 'Day Calls',
 'Day Charge',
 'Eve Mins',
 'Eve Calls',
 'Eve Charge',
 'Night Mins',
 'Night Calls',
 'Night Charge',
 'Intl Mins',
 'Intl Calls',
 'Intl Charge',
 'CustServ Calls',
 'Churn?']

In [ ]:
sublist=[x for x in all_columns_list if x not in desired_columns]
sublist

['State',
 'Area Code',
 "Int'l Plan",
 'VMail Plan',
 'VMail Message',
 'Day Mins',
 'Day Charge',
 'Eve Mins',
 'Eve Calls',
 'Night Mins',
 'Night Calls',
 'Night Charge',
 'Intl Mins',
 'Intl Calls',
 'Intl Charge',
 'CustServ Calls',
 'Churn?']

In [ ]:
#35
data3=data[data["Day Mins"]>300]
data3

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
15,NY,161,415,351-7269,no,no,0,332.9,67,56.59,...,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True.
76,DC,82,415,374-5353,no,no,0,300.3,109,51.05,...,100,15.39,270.1,73,12.15,11.7,4,3.16,0,True.
156,OH,83,415,370-9116,no,no,0,337.4,120,57.36,...,116,19.33,153.9,114,6.93,15.8,7,4.27,0,True.
197,TX,208,510,378-3625,no,no,0,326.5,67,55.51,...,113,14.99,181.7,102,8.18,10.7,6,2.89,2,True.
230,MD,93,408,360-3324,yes,no,0,312.0,109,53.04,...,100,11.00,217.6,74,9.79,10.5,2,2.84,0,True.
289,OK,89,510,352-6976,no,no,0,303.9,95,51.66,...,114,22.18,312.1,89,14.04,5.3,3,1.43,1,True.
365,CO,154,415,343-5709,no,no,0,350.8,75,59.64,...,94,18.40,253.9,100,11.43,10.1,9,2.73,1,True.
534,LA,67,510,373-6784,no,no,0,310.4,97,52.77,...,123,5.65,246.5,99,11.09,9.2,10,2.48,4,False.
575,SD,114,415,351-7369,no,yes,36,309.9,90,52.68,...,89,17.03,183.5,105,8.26,14.2,2,3.83,1,False.
605,MO,112,415,373-2053,no,no,0,335.5,77,57.04,...,109,18.06,265.0,132,11.93,12.7,8,3.43,2,True.
688,MN,13,510,338-7120,no,yes,21,315.6,105,53.65,...,71,17.76,260.1,123,11.70,12.1,3,3.27,3,False.
732,IN,48,510,342-6696,no,no,0,300.4,94,51.07,...,103,11.32,197.4,94,8.88,7.2,5,1.94,2,False.
815,KY,75,415,341-1191,no,no,0,314.6,102,53.48,...,86,14.43,285.1,100,12.83,5.7,3,1.54,2,True.
832,SC,87,408,335-1874,no,no,0,322.5,106,54.83,...,93,17.39,186.2,128,8.38,9.4,4,2.54,2,True.
901,CT,23,510,370-5527,no,no,0,321.6,107,54.67,...,115,21.39,141.1,158,6.35,11.3,3,3.05,2,True.
975,DE,129,510,332-6181,no,no,0,334.3,118,56.83,...,104,16.33,191.0,83,8.59,10.4,6,2.81,0,True.
985,NY,64,415,345-9140,yes,no,0,346.8,55,58.96,...,79,21.21,275.4,102,12.39,13.3,9,3.59,1,True.
1078,ME,80,408,333-7631,no,no,0,322.3,113,54.79,...,95,18.87,162.8,123,7.33,6.7,8,1.81,0,True.
1165,VT,50,415,387-5891,yes,yes,26,307.1,94,52.21,...,78,24.60,174.9,109,7.87,8.0,3,2.16,0,False.
1334,KS,126,408,379-8681,no,no,0,321.3,99,54.62,...,93,14.27,193.6,106,8.71,8.0,4,2.16,1,True.
1355,TX,50,408,330-6436,no,yes,31,302.7,93,51.46,...,119,20.44,193.9,103,8.73,13.6,14,3.67,3,False.
1679,OK,82,510,393-4823,no,no,0,329.8,73,56.07,...,120,17.71,267.1,102,12.02,10.6,6,2.86,0,True.
1830,CT,50,408,351-9037,no,no,0,301.7,82,51.29,...,118,14.20,72.2,89,3.25,10.5,6,2.84,1,False.
2028,SD,93,510,408-4836,no,no,0,328.1,106,55.78,...,89,12.89,303.5,114,13.66,8.7,3,2.35,1,True.
2215,MS,13,415,413-7468,no,no,0,303.2,133,51.54,...,86,14.49,227.6,80,10.24,11.5,3,3.11,0,True.
2259,NC,210,415,363-7802,no,yes,31,313.8,87,53.35,...,103,12.55,192.7,97,8.67,10.1,7,2.73,3,False.
2267,MS,29,510,401-6982,no,no,0,313.2,103,53.24,...,151,18.39,218.4,106,9.83,12.8,4,3.46,2,True.
2376,NV,42,415,352-5466,no,no,0,303.9,106,51.66,...,54,19.74,147.1,76,6.62,5.8,3,1.57,1,True.
2412,WI,89,415,373-4264,no,no,0,326.3,112,55.47,...,110,14.03,162.9,97,7.33,7.5,1,2.03,1,True.
2478,TN,123,415,415-3016,no,yes,34,305.2,80,51.88,...,109,13.30,280.0,81,12.60,13.2,7,3.56,1,False.
2572,MN,152,415,378-9542,no,no,0,317.8,60,54.03,...,100,13.00,123.4,63,5.55,10.4,7,2.81,1,True.
2573,WV,124,415,344-1970,no,no,0,312.0,112,53.04,...,109,15.30,168.6,94,7.59,12.8,4,3.46,1,True.
2594,OH,115,510,348-1163,yes,no,0,345.3,81,58.70,...,106,17.29,217.5,107,9.79,11.8,8,3.19,1,True.
2629,NH,141,415,402-3370,no,yes,32,322.4,92,54.81,...,107,24.07,209.5,111,9.43,6.7,3,1.81,1,True.
2660,NJ,88,415,347-8659,no,no,0,301.5,136,51.26,...,72,21.90,132.9,118,5.98,13.4,2,3.62,4,True.
2677,IA,44,415,359-7426,no,no,0,308.6,139,52.46,...,94,12.82,198.7,66,8.94,7.3,3,1.97,4,True.
2696,MI,74,415,359-6232,no,no,0,314.1,86,53.40,...,99,18.90,259.0,121,11.66,12.3,5,3.32,3,True.
2824,OR,81,415,406-4100,no,no,0,324.7,48,55.20,...,82,20.09,187.6,78,8.44,13.1,5,3.54,0,True.
2858,AL,141,510,388-8583,no,yes,28,308.0,123,52.36,...,128,21.06,152.9,103,6.88,7.4,3,2.00,1,False.
3072,TX,75,415,417-4456,no,no,0,305.1,106,51.87,...,115,15.98,235.4,116,10.59,8.5,5,2.30,0,True.
3132,NC,161,415,394-5489,no,no,0,322.3,100,54.79,...,135,19.58,241.5,104,10.87,7.8,5,2.11,2,True.
3207,DC,93,408,345-1994,no,yes,22,306.2,123,52.05,...,83,16.12,240.3,107,10.81,11.7,2,3.16,0,False.
3322,MD,62,408,409-1856,no,no,0,321.1,105,54.59,...,122,22.57,180.5,72,8.12,11.5,2,3.11,4,True.

In [ ]:
data3=data[data["State"]=='NY']
data3

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
15,NY,161,415,351-7269,no,no,0,332.9,67,56.59,...,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True.
77,NY,144,408,360-1171,no,no,0,61.6,117,10.47,...,85,6.55,173.0,99,7.79,8.2,7,2.21,4,True.
136,NY,75,415,374-8525,no,yes,21,175.8,97,29.89,...,106,18.49,237.5,134,10.69,5.3,4,1.43,5,False.
182,NY,67,408,405-2888,no,yes,36,115.6,111,19.65,...,94,20.20,169.9,103,7.65,9.9,12,2.67,2,False.
186,NY,106,408,422-1471,no,no,0,158.7,74,26.98,...,139,5.47,198.5,103,8.93,10.2,4,2.75,1,False.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3219,NY,150,415,421-6268,no,yes,35,139.6,72,23.73,...,170,28.29,213.8,105,9.62,8.8,2,2.38,2,False.
3227,NY,209,415,369-8703,no,no,0,153.7,105,26.13,...,87,16.03,200.8,95,9.04,10.7,2,2.89,0,False.
3257,NY,171,415,412-6245,no,no,0,137.5,110,23.38,...,109,16.84,292.7,131,13.17,13.3,5,3.59,2,False.
3275,NY,120,510,405-5083,no,yes,27,128.5,115,21.85,...,91,13.91,242.9,121,10.93,0.0,0,0.00,1,False.
3310,NY,94,415,363-1123,no,no,0,190.4,91,32.37,...,107,7.82,224.8,108,10.12,13.6,17,3.67,2,False.

In [ ]:
data3=data[(data["State"]=='NY') & (data["Day Mins"]>300)]
data3

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
15,NY,161,415,351-7269,no,no,0,332.9,67,56.59,...,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True.
985,NY,64,415,345-9140,yes,no,0,346.8,55,58.96,...,79,21.21,275.4,102,12.39,13.3,9,3.59,1,True.

In [ ]:
data4= data[(data['Day Mins']>300) | (data['State']=='NY')]
data4

#ASI FUNCIONA PARA < , > , | , &

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
15,NY,161,415,351-7269,no,no,0,332.9,67,56.59,...,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True.
76,DC,82,415,374-5353,no,no,0,300.3,109,51.05,...,100,15.39,270.1,73,12.15,11.7,4,3.16,0,True.
77,NY,144,408,360-1171,no,no,0,61.6,117,10.47,...,85,6.55,173.0,99,7.79,8.2,7,2.21,4,True.
136,NY,75,415,374-8525,no,yes,21,175.8,97,29.89,...,106,18.49,237.5,134,10.69,5.3,4,1.43,5,False.
156,OH,83,415,370-9116,no,no,0,337.4,120,57.36,...,116,19.33,153.9,114,6.93,15.8,7,4.27,0,True.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3227,NY,209,415,369-8703,no,no,0,153.7,105,26.13,...,87,16.03,200.8,95,9.04,10.7,2,2.89,0,False.
3257,NY,171,415,412-6245,no,no,0,137.5,110,23.38,...,109,16.84,292.7,131,13.17,13.3,5,3.59,2,False.
3275,NY,120,510,405-5083,no,yes,27,128.5,115,21.85,...,91,13.91,242.9,121,10.93,0.0,0,0.00,1,False.
3310,NY,94,415,363-1123,no,no,0,190.4,91,32.37,...,107,7.82,224.8,108,10.12,13.6,17,3.67,2,False.
3322,MD,62,408,409-1856,no,no,0,321.1,105,54.59,...,122,22.57,180.5,72,8.12,11.5,2,3.11,4,True.

In [ ]:
#36

#Minutos de dia, noche y long d2e la cuenta de los primeros 50 individuos
subset_first_50=data[["Day Mins","Night Mins","Account Length"]][:50]
subset_first_50.head(5)

   Day Mins  Night Mins  Account Length
0     265.1       244.7             128
1     161.6       254.4             107
2     243.4       162.6             137
3     299.4       196.9              84
4     166.7       186.9              75

In [ ]:
#PRimeras 10 filas, columnas de la 3 a la 6
data.iloc[1:10, 3:6]

      Phone Int'l Plan VMail Plan
1  371-7191         no        yes
2  358-1921         no         no
3  375-9999        yes         no
4  330-6626        yes         no
5  391-8027        yes         no
6  355-9993         no        yes
7  329-9001        yes         no
8  335-4719         no         no
9  330-8173        yes        yes

In [ ]:
data["Total Mins"]= data["Day Mins"]+ data["Eve Mins"]+data["Night Mins"]
data["Total Mins"]

0       707.2
1       611.5
2       527.2
3       558.2
4       501.9
        ...
3328    650.8
3329    575.8
3330    661.5
3331    512.6
3332    741.7
Name: Total Mins, Length: 3333, dtype: float64

In [ ]:
data["Total Calls"]=data["Day Calls"]+ data["Eve Calls"]+data["Night Calls"]
data["Total Mins"]

0       707.2
1       611.5
2       527.2
3       558.2
4       501.9
        ...
3328    650.8
3329    575.8
3330    661.5
3331    512.6
3332    741.7
Name: Total Mins, Length: 3333, dtype: float64

In [ ]:
#37
#Generación Aletario de Numeros
import numpy as np

#Generar un num alet de 1- 100
for i in range(10):
    print(np.random.randint(1,100))

59
96
74
31
97
5
63
92
85
20

In [ ]:
#Funciones de probabilidad